#! /usr/bin/env ruby
## -*- mode: ruby -*-
## = sample simulator for Oacis test
## Author:: Itsuki Noda
## Version:: 0.0 2020/02/01 I.Noda
##
## === History
## * [2020/02/01]: Create This File.
## * [YYYY/MM/DD]: add more
## == Usage
## just run
##    $ ./foo
## This read "_input.json" for parameter and write "_output.json" as a result.
## ...

def $LOAD_PATH.addIfNeed(path)
  self.unshift(path) if(!self.include?(path)) ;
end

# $LOAD_PATH.addIfNeed("~/lib/ruby");
# $LOAD_PATH.addIfNeed(File.dirname(__FILE__));

require 'optparse' ;
require 'pp' ;
require 'json' ;

#------------------------------------------------------------------------
#++
$conf = {
  :inFile => "_input.json",
  :outFile => "_output.json",
} ;

#----------------------------------------------------------------------
#++
## help
def help(raiseOrExit=true)
  puts($op) ;
  puts("Defaults:") ;
  pp $conf ;
  if(raiseOrExit.is_a?(Exception)||raiseOrExit.is_a?(String)) then
    puts('-' * 20) ;
    raise raiseOrExit ;
  elsif(raiseOrExit) then
    exit(1) ;
  end
end

#------------------------------------------------------------------------
#++
$op = OptionParser.new() {|op|
  op.banner = <<_END_
  Usage: #{$0} [Options]*
    This reads '_input.json' as a input parameter and
    writes '_output.json' as a result of simulation.
_END_

  op.separator("Options:") ;
  op.set_summary_indent("") ;
  op.set_summary_width(60) ;
  sep = "\n\t\t" ;

  op.on("--version", sep + "show version.") { 
    puts "0.0" ;
    exit(0) ;
  }
  op.on_tail("--help", sep + "show this message.") { 
    help() ;
  }
}

begin
  $op.parse!(ARGV) ;
rescue => ex
  help(ex) ;
end

$restArg = ARGV ;
p [:rest, ARGV], [:conf,$conf] ; 

########################################################################
########################################################################
########################################################################
param = nil ;

open($conf[:inFile],"r"){ |istrm|
  param = JSON.parse(istrm.read, { symbolize_names: true })
}

x = param[:x] ;
y = param[:y] ;
z = param[:z] ;

u = x + y - z ;
v = (x + 1) * (y + 2) * (z + 3) ;
w = (x - y) * (y - z) * (z - x) ;

result = {
  :u => u,
  :v => v,
  :w => w
} ;

pp ({:param => param, :result => result}) ;

open($conf[:outFile],"w"){ |ostrm|
  ostrm << JSON.pretty_generate(result) << "\n" ;
}


